### ISSUE TITLE
What is the point of this?

### ISSUE THREAD

**Issue by knopp** [blackmenthor/flutter-android-lifecycle-plugin#1]
How is this different from using `WidgetsBindingObserver`?

**Comment by blackmenthor** [comment]
basically the inspiration was i needed to call some kotlin function inside Android's onStart callback from dart

**Comment by Tokenyet** [comment]
In my test, this plugin works better than original(flutter's two method) on Android, you could hook your functions before or after `runApp`. (I mean anywhere)

`SystemChannels` works fine after runApp, <s>and I have no idea why `WidgetsBindingObserver` is not working both in my case 🤕 </s>

Never mind, I forgot to addObserver 🤐
