### ISSUE TITLE
Compatibility issues when using local_auth

### ISSUE THREAD

**Issue by andrewpmoore** [blackmenthor/flutter-android-lifecycle-plugin#4]
The local_auth package used for biometrics doesn't work when this package is used because it depends on FlutterFragmentActivity but this package uses FlutterActivity. Is there  a way to change it to extend the fragment activity instead. We are needing this to get the branch package (which relies on this) to work in addition to local_auth.

**Comment by blackmenthor** [comment]
sorry for the late reply, `FragmentActivity` is now included on the latest version.

Closing this.
